### ISSUE TITLE
why  is there no demo use the last version of overlap2d-runtime-libgdx?

### ISSUE THREAD

**Issue by tianqiujie** [UnderwaterApps/overlap2d-runtime-libgdx#50]
I am crazy, there is no document about use the overlap2d-runtime-libgdx

such as : how to use the ButtonComponent

**Comment by azakhary** [comment]
Sorry about that, reason we don't have a documentation is because new runtime is well, very new. And we are just several guys working at our spare time for free.

But, we do have a sample project I made, that shows how to use ButtonComponent. it's not a big project, so it will be easy to find:

https://github.com/azakhary/useless_deer

Check : UselessDeer.java - line 38
